version: "3.7"
services:
  server:
    build: ./
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./app:/code/app
    ports:
      - 8000:8000
    networks:
      AIservice:
        aliases:
          - server.docker
  frontend:
    build: ./
    ports:
      - 3000:3000
    networks:
      AIservice:
        aliases:
          - frontend.docker
    depends_on:
      - server
networks:
  AIservice:
    external: true