# Use a base image with Node.js installed
FROM node:14

# Set the working directory
WORKDIR /app/frontend

# Copy the package.json and package-lock.json files
COPY package*.json ./

# Install the dependencies
RUN npm install

# Copy the frontend source code
COPY ./frontend .

# Build the frontend application
RUN npm run build

# Specify the command to start the development server
CMD ["npm", "start"]
