version: "3.7"
services:
  server:
    build: ./
    ports:
      - 8000:8000
    networks:
      AIservice:
        aliases:
          - server.docker
  frontend:
    build: ./
    ports:
      - 3000:3000
    networks:
      AIservice:
        aliases:
          - frontend.docker
    depends_on:
      - server
networks:
  AIservice:
    external: true
